repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args:
          - "--profile"
          - black
        name: isort
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
