# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: python-redsys

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint and format with ruff
      run: |
        poetry run ruff . --fix --exit-non-zero-on-fix
        poetry run ruff format . --check
    - name: Test with pytest
      run: |
        poetry run pytest
